Bump jvm from 1.7.10 to 1.7.20 (#930)
Bumps [jvm](https://github.com/JetBrains/kotlin) from 1.7.10 to 1.7.20.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/JetBrains/kotlin/releases">jvm's
releases</a>.</em></p>
<blockquote>
<h2>Kotlin 1.7.20</h2>
<h2>1.7.20</h2>
<h3>Analysis API</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-52667"><code>KT-52667</code></a>
FIR IDE: fun interfaces (SAM interfaces) are not properly resolved</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-52136"><code>KT-52136</code></a>
FIR: Implicit type declaration from the other module cannot be used for
overloading</li>
</ul>
<h3>Analysis API. FE1.0</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-51962"><code>KT-51962</code></a>
Analysis API: Finish Analysis API for FE1.0</li>
</ul>
<h3>Analysis API. FIR</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-52779"><code>KT-52779</code></a>
FIR IDE: Import Optimizer cannot handle generic type qualifiers</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-50236"><code>KT-50236</code></a>
Fix OOB modification trackers for non-Kotlin code</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-51240"><code>KT-51240</code></a>
Analysis API: KtAnalysisSession for a specific module cannot create a
symbol for PSI that cannot be seen from that module.</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-50868"><code>KT-50868</code></a>
Analysis API: decompiled type aliases are not resolved</li>
</ul>
<h3>Compiler</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-53739"><code>KT-53739</code></a>
Builder inference, extension hides members</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-53733"><code>KT-53733</code></a>
Kotlin/Native: update source documentation for the new default memory
manager</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-53667"><code>KT-53667</code></a>
Compiler crashes on attempt to alloc a string on the stack in new
MM</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-53480"><code>KT-53480</code></a>
Internal error in file lowering: java.lang.ClassNotFoundException:
com.android.systemui.R$string</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-52843"><code>KT-52843</code></a>
Compose: NPE at Parameters.getParameterByDeclarationSlot if inline
function with default arguments takes a lambda which captures value
class represented by Long</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-51868"><code>KT-51868</code></a>
JVM / IR: Inconsistent behaviour between lambda expression and SAM
interface conversion for the same interface</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-53475"><code>KT-53475</code></a>
Kotlin/Native for iOS: &quot;IllegalArgumentException: Sequence has more
than one element&quot;</li>
</ul>
<h4>New Features</h4>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-52495"><code>KT-52495</code></a>
Support until operator in back-ends</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-52420"><code>KT-52420</code></a>
Implement resolve of until operator</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-52419"><code>KT-52419</code></a>
Implement until operator in the parser</li>
<li>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-33755"><code>KT-33755</code></a>
Kotlin/Native: Provide a way to customize a bundle Identifier of a
generated framework</li>
</ul>
</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-51665"><code>KT-51665</code></a>
FIR: implement label resolve for &quot;typed this&quot; case</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-52361"><code>KT-52361</code></a>
Report warning on potentially empty intersection types</li>
</ul>
<h4>Performance Improvements</h4>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-47816"><code>KT-47816</code></a>
Disable script discovery for non-script environments</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-48635"><code>KT-48635</code></a>
JVM IR: Double/Float values are boxed when comparing for equality in
equals method of data/value classes</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-23397"><code>KT-23397</code></a>
Optimize out field for property delegate when it's safe (JVM)</li>
</ul>
<h4>Fixes</h4>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-53272"><code>KT-53272</code></a>
Backend Internal error: Exception during IR lowering / No such value
argument slot: 2</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-53124"><code>KT-53124</code></a>
Receiver type mismatch when combining extension properties, type
projections, Java sources, and F-bounded type-variables</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-51868"><code>KT-51868</code></a>
JVM / IR: Inconsistent behaviour between lambda expression and SAM
interface conversion for the same interface</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-36770"><code>KT-36770</code></a>
Prohibit unsafe calls with expected <code>@NotNull</code> T and given
Kotlin generic parameter with nullable bound</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-52974"><code>KT-52974</code></a>
&quot;IllegalStateException: Symbol with IrSimpleFunctionSymbolImpl is
unbound&quot; compiling native targets of MPP project</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/JetBrains/kotlin/blob/v1.7.20/ChangeLog.md">jvm's
changelog</a>.</em></p>
<blockquote>
<h2>1.7.20</h2>
<h3>Compiler</h3>
<h4>New Features</h4>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-52495"><code>KT-52495</code></a>
Support until operator in back-ends</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-52420"><code>KT-52420</code></a>
Implement resolve of until operator</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-52419"><code>KT-52419</code></a>
Implement until operator in the parser</li>
</ul>
<h4>Fixes</h4>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-53947"><code>KT-53947</code></a>
IllegalStateException: No mapping for symbol: VALUE_PARAMETER
INSTANCE_RECEIVER</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-51234"><code>KT-51234</code></a>
Context receivers can be duplicated in function declaration</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-51576"><code>KT-51576</code></a>
Context receivers: &quot;AssertionError: Callers must check that current
token is IDENTIFIER followed with '@'&quot; with <code>at</code>
character</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-49479"><code>KT-49479</code></a>
JVM / IR: &quot;IllegalStateException: IrErrorType&quot; during IR
lowering with non-trivial recursion calls</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-52270"><code>KT-52270</code></a>
NullPointerException caused by braces on if-else returning a method
reference inside lambda</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-47621"><code>KT-47621</code></a>
False negative INVISIBLE_MEMBER on call to inaccessible protected
synthetic property setter</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-37796"><code>KT-37796</code></a>
NI: &quot;ISE: Error type encountered&quot; when inferring type of a
property that delegates to itself</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-45430"><code>KT-45430</code></a>
PSI2IR:
&quot;org.jetbrains.kotlin.psi2ir.generators.ErrorExpressionException:
null: KtCallExpression: toString()&quot; with recursive function call in
&quot;also&quot; block in nontrivial context</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-52691"><code>KT-52691</code></a>
K2: Expected FirResolvedTypeRef with ConeKotlinType but was
FirImplicitTypeRefImpl with intertwined functional interfaces</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-52822"><code>KT-52822</code></a>
Fix contract for KtElement.getReference()</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-50223"><code>KT-50223</code></a>
IndexOutOfBoundsException from
<code>ClassicTypeSystemContext$DefaultImpls.getParameter</code> during
call resolution</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-51963"><code>KT-51963</code></a>
Change Maven version to 1.7.255</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-47664"><code>KT-47664</code></a>
Incorrect type checking in the case of generic types</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-48765"><code>KT-48765</code></a>
NI: Inferred type does not respect the bound of type variable</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-51243"><code>KT-51243</code></a>
False positive error &quot;No required context receiver&quot; inside
contextual lambda</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-43541"><code>KT-43541</code></a>
TYPE_MISMATCH for member function which is not occur for top level
function during unsafe cast</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-51016"><code>KT-51016</code></a>
[FIR] False positive OVERLOAD_RESOLUTION_AMBIGUITY between two
extensions on different supertypes</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-50155"><code>KT-50155</code></a>
FIR: support contextual receivers</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-38637"><code>KT-38637</code></a>
Catch NoSuchFieldException in optimized when expression over enum</li>
</ul>
<h3>Docs &amp; Examples</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-49896"><code>KT-49896</code></a>
Kotlin/JS: improve <code>-Xir-property-lazy-initialization</code>
description due to making it true by default</li>
</ul>
<h3>IDE</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KTIJ-22286"><code>KTIJ-22286</code></a>
Kotlin JPS project created via wizard does not contain Kotlin libraries
in case of not-released version</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KTIJ-22065"><code>KTIJ-22065</code></a>
IDE notification motivating Kotlin users to use EAP</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KTIJ-22209"><code>KTIJ-22209</code></a>
Configure Kotlin on 221 idea adds 1.6.10 Kotlin (despite the fact that
IDE plugin is 1.7.10)</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KTIJ-22171"><code>KTIJ-22171</code></a>
Fix test BuiltInDecompilerConsistencyTest</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KTIJ-22016"><code>KTIJ-22016</code></a>
Empty .kt file and build.gradle.kts can trigger an error while searching
for a facade light class</li>
</ul>
<h3>IDE. Code Style, Formatting</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KTIJ-21346"><code>KTIJ-21346</code></a>
Incorrect formatting for functions with context receivers and visibility
modifiers</li>
</ul>
<h3>IDE. Completion</h3>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/JetBrains/kotlin/commit/7159702d253166e43f15736f3dfb81bcad68f4a4"><code>7159702</code></a>
Add changelog for 1.7.20</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/9ca25ce335d7e443f146bd47c6e3c2e6fae0c15c"><code>9ca25ce</code></a>
Native: add more tests for Swift Set and Dictionary used in Kotlin</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/1244679230e204a3f90d2ceaea4b2099f24ea4e7"><code>1244679</code></a>
Native: improve thread state switches for NSSet/NSDictionary
adapters</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/1abfeb96d4df66acf762a626f597a3a443933c12"><code>1abfeb9</code></a>
[Gradle][MPP] MPP/AGP compatibility: Bump maxSupportedVersion to
7.3</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/b489e935080d31f0c488373ed0f57d1ddce27e2b"><code>b489e93</code></a>
Fix lowering of receiver access in IR scripting</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/8a8853cdef60f54d072d355b4c48c35e086e0091"><code>8a8853c</code></a>
K1. Fix error message for
BUILDER_INFERENCE_MULTI_LAMBDA_RESTRICTION</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/608d45c524493f1c4c5fc6740e38fe44de6af06b"><code>608d45c</code></a>
Add changelog for 1.7.20-RC</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/3a340d2448be5c06e375de592ea29c2890c25389"><code>3a340d2</code></a>
Fix kind of NoBuilderInferenceWithoutAnnotationRestriction</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/a17fc51b9f846ad8e7ddfe76ca8fc17ea31a4d26"><code>a17fc51</code></a>
Fix receiver inconsistency when builder inference restriction
disabled</li>
<li><a
href="https://github.com/JetBrains/kotlin/commit/f0fd2cfd647d61398d3d027f7c9ece414a4c8292"><code>f0fd2cf</code></a>
Put back the line with language feature to 1.7 block</li>
<li>Additional commits viewable in <a
href="https://github.com/JetBrains/kotlin/compare/v1.7.10...v1.7.20">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=jvm&package-manager=gradle&previous-version=1.7.10&new-version=1.7.20)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>